config/routes.rb
PBackend::Application.routes.draw do
  resources :scene_templates

  resources :redeemed_vouchers

  resources :vouchers

  resources :reviews

  resources :video_files

  resources :scenes

  resources :review_templates

  resources :products

  resources :brands

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/redeemed_voucher.rb
class RedeemedVoucher < ActiveRecord::Base
  belongs_to :user
  belongs_to :voucher
end

app/controllers/redeemed_vouchers_controller.rb
class RedeemedVouchersController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_redeemed_voucher, only: [:show, :edit, :update, :destroy]

  # GET /redeemed_vouchers
  # GET /redeemed_vouchers.json
  def index
    @redeemed_vouchers = RedeemedVoucher.all
  end

  # GET /redeemed_vouchers/1
  # GET /redeemed_vouchers/1.json
  def show
  end

  # GET /redeemed_vouchers/new
  def new
    @redeemed_voucher = RedeemedVoucher.new
  end

  # GET /redeemed_vouchers/1/edit
  def edit
  end

  # POST /redeemed_vouchers
  # POST /redeemed_vouchers.json
  def create
    @redeemed_voucher = RedeemedVoucher.new(redeemed_voucher_params)
    @redeemed_voucher.user = current_user

    respond_to do |format|
      if @redeemed_voucher.save
        format.html { redirect_to @redeemed_voucher, notice: 'Redeemed voucher was successfully created.' }
        format.json { render action: 'show', status: :created, location: @redeemed_voucher }
      else
        format.html { render action: 'new' }
        format.json { render json: @redeemed_voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /redeemed_vouchers/1
  # PATCH/PUT /redeemed_vouchers/1.json
  def update
    respond_to do |format|
      if @redeemed_voucher.update(redeemed_voucher_params)
        format.html { redirect_to @redeemed_voucher, notice: 'Redeemed voucher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @redeemed_voucher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /redeemed_vouchers/1
  # DELETE /redeemed_vouchers/1.json
  def destroy
    @redeemed_voucher.destroy
    respond_to do |format|
      format.html { redirect_to redeemed_vouchers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_redeemed_voucher
      @redeemed_voucher = RedeemedVoucher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def redeemed_voucher_params
      params.require(:redeemed_voucher).permit(:user_id, :voucher_id)
    end
end

app/helpers/redeemed_vouchers_helper.rb
module RedeemedVouchersHelper
end

app/views/redeemed_vouchers/_form.html.erb
<%= form_for(@redeemed_voucher) do |f| %>
  <% if @redeemed_voucher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@redeemed_voucher.errors.count, "error") %> prohibited this redeemed_voucher from being saved:</h2>

      <ul>
      <% @redeemed_voucher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :voucher_id %><br>
    <%= f.text_field :voucher_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/redeemed_vouchers/edit.html.erb
<h1>Editing redeemed_voucher</h1>

<%= render 'form' %>

<%= link_to 'Show', @redeemed_voucher %> |
<%= link_to 'Back', redeemed_vouchers_path %>

app/views/redeemed_vouchers/index.html.erb
<h1>Listing redeemed_vouchers</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Voucher</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @redeemed_vouchers.each do |redeemed_voucher| %>
      <tr>
        <td><%= redeemed_voucher.user %></td>
        <td><%= redeemed_voucher.voucher %></td>
        <td><%= link_to 'Show', redeemed_voucher %></td>
        <td><%= link_to 'Edit', edit_redeemed_voucher_path(redeemed_voucher) %></td>
        <td><%= link_to 'Destroy', redeemed_voucher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Redeemed voucher', new_redeemed_voucher_path %>

app/views/redeemed_vouchers/new.html.erb
<h1>New redeemed_voucher</h1>

<%= render 'form' %>

<%= link_to 'Back', redeemed_vouchers_path %>

app/views/redeemed_vouchers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @redeemed_voucher.user %>
</p>

<p>
  <strong>Voucher:</strong>
  <%= @redeemed_voucher.voucher %>
</p>

<%= link_to 'Edit', edit_redeemed_voucher_path(@redeemed_voucher) %> |
<%= link_to 'Back', redeemed_vouchers_path %>