config/routes.rb
PBackend::Application.routes.draw do
  resources :scene_templates

  resources :redeemed_vouchers

  resources :vouchers

  resources :reviews

  resources :video_files

  resources :scenes

  resources :review_templates

  resources :products

  resources :brands

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  
  devise_scope :user do
    get    "login"   => "devise/sessions#new",         as: :new_user_session
    post   "login"   => "devise/sessions#create",      as: :user_session
    delete "signout" => "devise/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "devise/registrations#new",    as: :new_user_registration
    post   "signup"  => "devise/registrations#create", as: :user_registration
    put    "signup"  => "devise/registrations#update", as: :update_user_registration
    get    "account" => "devise/registrations#edit",   as: :edit_user_registration
  end

end

app/models/scene.rb
class Scene < ActiveRecord::Base
  belongs_to :review
  belongs_to :scene_template
  has_many :video_files
end

app/controllers/scenes_controller.rb
class ScenesController < ApplicationController
  before_action :set_scene, only: [:show, :edit, :update, :destroy]

  # GET /scenes
  # GET /scenes.json
  def index
    @scenes = Scene.all
  end

  # GET /scenes/1
  # GET /scenes/1.json
  def show
  end

  # GET /scenes/new
  def new
    @scene = Scene.new
  end

  # GET /scenes/1/edit
  def edit
  end

  # POST /scenes
  # POST /scenes.json
  def create
    @scene = Scene.new(scene_params)

    respond_to do |format|
      if @scene.save
        format.html { redirect_to @scene, notice: 'Scene was successfully created.' }
        format.json { render action: 'show', status: :created, location: @scene }
      else
        format.html { render action: 'new' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scenes/1
  # PATCH/PUT /scenes/1.json
  def update
    respond_to do |format|
      if @scene.update(scene_params)
        format.html { redirect_to @scene, notice: 'Scene was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @scene.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scenes/1
  # DELETE /scenes/1.json
  def destroy
    @scene.destroy
    respond_to do |format|
      format.html { redirect_to scenes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scene
      @scene = Scene.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scene_params
      params.require(:scene).permit(:review_id, :sort_order, :max_length, :name, :description, :scene_template_id)
    end
end

app/helpers/scenes_helper.rb
module ScenesHelper
end

app/views/scenes/_form.html.erb
<%= form_for(@scene) do |f| %>
  <% if @scene.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scene.errors.count, "error") %> prohibited this scene from being saved:</h2>

      <ul>
      <% @scene.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :review_id %><br>
    <%= f.text_field :review_id %>
  </div>
  <div class="field">
    <%= f.label :sort_order %><br>
    <%= f.number_field :sort_order %>
  </div>
  <div class="field">
    <%= f.label :max_length %><br>
    <%= f.number_field :max_length %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :scene_template_id %><br>
    <%= f.text_field :scene_template_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scenes/edit.html.erb
<h1>Editing scene</h1>

<%= render 'form' %>

<%= link_to 'Show', @scene %> |
<%= link_to 'Back', scenes_path %>

app/views/scenes/index.html.erb
<h1>Listing scenes</h1>

<table>
  <thead>
    <tr>
      <th>Review</th>
      <th>Sort order</th>
      <th>Max length</th>
      <th>Name</th>
      <th>Description</th>
      <th>Scene template</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @scenes.each do |scene| %>
      <tr>
        <td><%= scene.review %></td>
        <td><%= scene.sort_order %></td>
        <td><%= scene.max_length %></td>
        <td><%= scene.name %></td>
        <td><%= scene.description %></td>
        <td><%= scene.scene_template %></td>
        <td><%= link_to 'Show', scene %></td>
        <td><%= link_to 'Edit', edit_scene_path(scene) %></td>
        <td><%= link_to 'Destroy', scene, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scene', new_scene_path %>

app/views/scenes/new.html.erb
<h1>New scene</h1>

<%= render 'form' %>

<%= link_to 'Back', scenes_path %>

app/views/scenes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Review:</strong>
  <%= @scene.review %>
</p>

<p>
  <strong>Sort order:</strong>
  <%= @scene.sort_order %>
</p>

<p>
  <strong>Max length:</strong>
  <%= @scene.max_length %>
</p>

<p>
  <strong>Name:</strong>
  <%= @scene.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @scene.description %>
</p>

<p>
  <strong>Scene template:</strong>
  <%= @scene.scene_template %>
</p>

<%= link_to 'Edit', edit_scene_path(@scene) %> |
<%= link_to 'Back', scenes_path %>